use_frameworks!

platform :ios, '9.0'

target 'GJTUserCenterModule_Example' do
  pod 'GJTUserCenterModule', :path => '../'

  target 'GJTUserCenterModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
